### ISSUE TITLE
Simple D3 library adapter to Geoservices

### ISSUE THREAD

**Issue by ajturner** [chelm/esri-d3#18]
While this library is nice for loading a GeoJSON file using D3 as a layer in the JS API - the reverse would also be nice.

Given a FeatureService URL, provide a simple method to load the service into D3 for subsequent chaining into other Cartographic and non-cartographic visualizations. 

For example, can you use this [US Underground Natural Gas Storage Facilities](http://www.arcgis.com/home/item.html?id=c059aaf8afc9490ba001287a28392915) to create an interactive bubble visualization (or other)

**Comment by jgravois** [comment]
@ajturner and the rest did the hard part ([cedar](https://esri.github.io/cedar)).  I'll do the easy part. :bowtie:
