### ISSUE TITLE
TypeError in Samples

### ISSUE THREAD

**Issue by rmumford** [chelm/esri-d3#19]
Hi, 

I am having some problems loading the samples in this project. Let's use the 'rules.html' as an example, though they are all behaving the same way for me. 

So occasionally, the page will load successfully and the states appear on the map. But then, if I refresh the page, it fails to load completely. If I open the console in the browser, I see there is a TypeError of:

'modules.d3Layer is not a constructor'

This is how it behaves the majority of the time, but every so often, it will work again. 

I have tried this on Chrome and Firefox and I have run both local copies and the ones you have hosted. All result in the same behaviour. 

Do you have any ideas what could be happening? 

Thanks in advance!

**Comment by jgravois** [comment]
sorry for the extremely belated reply, but i made some changes/updates in november/[december](https://github.com/chelm/esri-d3/pull/22) of 2014 which should have resolved these errors. 

if you could confirm, that'd be swell.
